"""add_detector_type_to_scans

Revision ID: a409d81e2f55
Revises: a59e040d4251
Create Date: 2026-03-30 17:56:59.376785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a409d81e2f55'
down_revision: Union[str, None] = 'a59e040d4251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detector_type', sa.String(length=20), nullable=False, server_default='gdino'))
        batch_op.alter_column('llm_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'openai'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('llm_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'openai'"))
        batch_op.drop_column('detector_type')

    # ### end Alembic commands ###
