"""add phone field and push_subscriptions

Revision ID: a59e040d4251
Revises: 8c23d33ba34c
Create Date: 2026-03-23 10:10:33.471977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59e040d4251'
down_revision: Union[str, None] = '8c23d33ba34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
